version: "3.8"
services: 
#all service grouped together will run in the same network
  mongodb:
    image: mongo:latest
    volumes: 
      - mongodbdata:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=mymongoadmin
    #   - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword
    #   - MONGO_INITDB_DATABASE=admin
    env_file: 
      - ./env/mongo.env
    container_name: mongodb
    command: [--auth]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend/src:/app/src
    ports: 
      - 8000:8000
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    container_name: backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend/src:/app/src
    ports: 
      - 3000:3000
    env_file:
      - ./env/frontend.env
    container_name: frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodbdata: